name: conductor
description: "Conductor: An event-driven, deterministic, state-machine based library for managing interaction between various components of a Flutter app."
version: 0.0.7
repository: https://github.com/ARK4579/conductor

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.2.0
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.4.0
  go_router: ^13.2.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  os_detect: ^2.0.1
  path: ^1.8.3
  path_provider: ^2.1.1
  riverpod: ^2.4.0
  sembast: ^3.5.0+1
  sembast_web: ^2.1.3
  uuid: ^4.2.1
  intl: ^0.19.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
