name: conductor
description: "Conductor: An event-driven, deterministic, state-machine based library for managing interaction between various components of a Flutter app."
version: 0.0.1
repository: https://github.com/ARK4579/conductor

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
